### ISSUE TITLE
IsarError: Cannot open Environment: MdbxError (38): Function not implemented

### ISSUE THREAD

**Issue by thorito** [isar-community/isar#112]
### Steps to Reproduce

I'm reporting a bug on Crashlytics for a OnePlus device, running Android 11

```sh

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: IsarError: Cannot open Environment: MdbxError (38): Function not implemented. Error thrown Error detected in runZonedGuarded.
#00 pc 0x81cc7b com.thorito.example (FirebaseCrashlytics.recordError [firebase_crashlytics.dart:119]) (BuildId: 63956a45f814b3c910d24405fe4de070)
#01 pc 0x869e77 com.thorito.example (main.<anonymous closure> [main.dart:56]) (BuildId: 63956a45f814b3c910d24405fe4de070)
#02 pc 0x869c07 com.thorito.example (runZonedGuarded.<anonymous closure> [zone.dart:1666]) (BuildId: 63956a45f814b3c910d24405fe4de070)
#03 pc 0x7b3eb7 com.thorito.example (_Zone._processUncaughtError [zone.dart:1081]) (BuildId: 63956a45f814b3c910d24405fe4de070)
#04 pc 0x26e0ef com.thorito.example (Future._propagateToListeners [zone.dart:1285]) (BuildId: 63956a45f814b3c910d24405fe4de070)
#05 pc 0x26e1e7 com.thorito.example (Future._completeError [future_impl.dart:674]) (BuildId: 63956a45f814b3c910d24405fe4de070)
#06 pc 0x79ccdb com.thorito.example (_SuspendState._handleException [async_patch.dart:425]) (BuildId: 63956a45f814b3c910d24405fe4de070)
        
```

### Code sample

```dart
class IsarHelper {
  // Singleton pattern
  static IsarHelper? _isar;
  static Isar? _isarDb;

  static IsarHelper get instance => _isar ??= const IsarHelper._internal();

  Isar get isar => _isarDb!;

  const IsarHelper._internal();

  Future<void> init() async {
    if (_isarDb != null) return;

    final path = (await getApplicationDocumentsDirectory()).path;
    _isarDb = await Isar.open(
      [
        NotificationDbSchema,
        MqttLocalMessageSchema,
      ],
      directory: path,
    );
  }
}
```

### Details

 - Platform: OnePlus8Pro SDK: 11
 - Flutter version: Channel stable, 3.24.5
 - Isar version: ^3.1.8

Marca:OnePlus
Model: OnePlus8Pro
Orientation: Vertical
Available RAM: 1.97 GB
Available disk space: 2.86 GB

```yaml
dependencies:
  
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
```

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by ductranit** [comment]
I have the same crash report. Does anyone know how to workaround?

**Comment by erthink** [comment]
Most likely the Linux kernel and/or `libc` (aka Bionic) a target device didn't supports some syscall or feature required/used by [libmdbx](https://libmdbx.dqdkfa.ru/) (the underlining key-value storage engine).

As the main developer/maintainer of _libmdbx_, I can help you with this and even make some up works:

1. Please use/try the latest stable release of libmdbx (v0.13.5 at the moment).
2. Provide exactly information about the Linux kernel and libc (Bionic) version from a target device. 
   - Current versions of libmdbx require kernel version 4.x or later, but I can consider supporting older kernels if someone is interested enough to provide proper testing over a whole lifecycle.
   - I am not ready to voice the requirement for the minimum version of libc (Bionic) or the NDK level right now, since there were quite a lot of flaws, bugs and other glitches in all old versions, including in the toolchain. Noneteless, I can provide Android support to a reasonable version depth if someone provides automated testing (a CI environment with a test suite).
3. Provide a debug logging from libmdbx, see [`mdbx_setup_debug()`](https://libmdbx.dqdkfa.ru/group__c__debug.html#gaf29c22b078ce477d181a399cc251d860).
4. Use a debug build of libmdbx (`-DMDBX_DEBUG=1`).
5. Be ready to use [strace](https://source.android.com/docs/core/tests/debug/strace?hl=en#app-strace).
