### ISSUE TITLE
Data migration from v3 to v4 not working yet

### ISSUE THREAD

**Issue by mrclauss** [isar-community/isar#21]
### Steps to Reproduce

Adapt an existing project with an existing database to v4/main

Opening the database results in some deserialisation error:

E/flutter ( 1821): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Schema error: Could not deserialize existing schema.
E/flutter ( 1821): #0      _extension#14.throwError (package:isar/src/impl/native_error.dart:32:11)
E/flutter ( 1821): #1      _extension#14.checkNoError (package:isar/src/impl/native_error.dart:7:7)
E/flutter ( 1821): #2      new _IsarImpl.open (package:isar/src/impl/isar_impl.dart:100:10)
E/flutter ( 1821): #3      Isar.open (package:isar/src/isar.dart:88:28)
E/flutter ( 1821): #4      CtaDB._init (package:contactulater/db/ctadb.dart:70:21)
E/flutter ( 1821): <asynchronous suspension>
E/flutter ( 1821): #5      CtaCore.init (package:contactulater/ctacore.dart:272:5)
E/flutter ( 1821): <asynchronous suspension>
E/flutter ( 1821): #6      mymain (package:contactulater/ui/loader.dart:109:3)
E/flutter ( 1821): <asynchronous suspension>

### Code sample

```dart
Provide a few simple lines of code to show your problem.
```

### Details

 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: [e.g. 3.0.0]
 - Isar version: [e.g. 2.5.0]

---

 - [ ] I searched for similar issues already
 - [ ] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by mohachouch** [comment]
Hello @mrclauss, we are using Isar in an production. We can't upgrade to isar 4 without migration. If we need help for testing or something else. Let me know
